# Generated by Django 4.0.6 on 2022-07-24 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile', models.TextField()),
                ('has_logo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('industry_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('function', models.CharField(max_length=64)),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('department', models.CharField(max_length=64)),
                ('benefits', models.TextField()),
                ('description', models.TextField()),
                ('fraudulent', models.BooleanField(default=False)),
                ('telecommuting', models.BooleanField(default=False)),
                ('has_question', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=24)),
                ('state', models.CharField(max_length=24)),
                ('country', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('description', models.TextField()),
                ('education', models.CharField(max_length=24)),
                ('experience', models.CharField(max_length=24)),
                ('employment_type', models.CharField(max_length=24)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jobposting.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='located_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobposting.location'),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobposting.company'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobposting.industry'),
        ),
    ]
